### ISSUE TITLE
Berryboot update

### ISSUE THREAD

**Issue by actraiser30** [radimkohout/berryboot-new#1]
Hello there,is it possible to release an updated berryboot version?

Thanks in advance

**Comment by radimkohout** [comment]
Hi,
sorry for not replying. I am not original author, but I've tried to do that, but failed, at least for the moment. I've replaced berryboot on my devices by native Debian system on RPi.

**Comment by actraiser30** [comment]
Hi no problem

Is it possible to build an older berryboot version based for example in 5.10.83 or 5.10.103 kernel that is the last kernel version used in Raspbian buster?? In other words do not build the latest 6.1 kernel but an older one that still will be newer than the current one.

Thanks
